# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chibu.grpc_server import chibu_agent_pb2 as chibu__agent__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chibu_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChiAgentStub(object):
    """ChiAgent — gRPC service exposed by each Pi agent instance
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_stream(
                '/chibu.ChiAgent/Execute',
                request_serializer=chibu__agent__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=chibu__agent__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.GetInfo = channel.unary_unary(
                '/chibu.ChiAgent/GetInfo',
                request_serializer=chibu__agent__pb2.InfoRequest.SerializeToString,
                response_deserializer=chibu__agent__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.ListSkills = channel.unary_unary(
                '/chibu.ChiAgent/ListSkills',
                request_serializer=chibu__agent__pb2.ListSkillsRequest.SerializeToString,
                response_deserializer=chibu__agent__pb2.ListSkillsResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/chibu.ChiAgent/Ping',
                request_serializer=chibu__agent__pb2.PingRequest.SerializeToString,
                response_deserializer=chibu__agent__pb2.PongResponse.FromString,
                _registered_method=True)


class ChiAgentServicer(object):
    """ChiAgent — gRPC service exposed by each Pi agent instance
    """

    def Execute(self, request, context):
        """Execute an agent with a prompt, streaming back events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInfo(self, request, context):
        """Retrieve agent identity and capability metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSkills(self, request, context):
        """List skills available on this agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChiAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=chibu__agent__pb2.ExecuteRequest.FromString,
                    response_serializer=chibu__agent__pb2.ExecuteResponse.SerializeToString,
            ),
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=chibu__agent__pb2.InfoRequest.FromString,
                    response_serializer=chibu__agent__pb2.InfoResponse.SerializeToString,
            ),
            'ListSkills': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSkills,
                    request_deserializer=chibu__agent__pb2.ListSkillsRequest.FromString,
                    response_serializer=chibu__agent__pb2.ListSkillsResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=chibu__agent__pb2.PingRequest.FromString,
                    response_serializer=chibu__agent__pb2.PongResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chibu.ChiAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chibu.ChiAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChiAgent(object):
    """ChiAgent — gRPC service exposed by each Pi agent instance
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chibu.ChiAgent/Execute',
            chibu__agent__pb2.ExecuteRequest.SerializeToString,
            chibu__agent__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chibu.ChiAgent/GetInfo',
            chibu__agent__pb2.InfoRequest.SerializeToString,
            chibu__agent__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSkills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chibu.ChiAgent/ListSkills',
            chibu__agent__pb2.ListSkillsRequest.SerializeToString,
            chibu__agent__pb2.ListSkillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chibu.ChiAgent/Ping',
            chibu__agent__pb2.PingRequest.SerializeToString,
            chibu__agent__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
