"""initial schema

Revision ID: cc1f4fd6ae26
Revises: 
Create Date: 2026-04-24 21:50:12.336305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1f4fd6ae26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=240), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_agent_id'), 'agent_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_events_created_at'), 'agent_events', ['created_at'], unique=False)
    op.create_table('agent_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=240), nullable=False),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_agent_id'), 'performance_metrics', ['agent_id'], unique=False)
    op.create_index(op.f('ix_performance_metrics_recorded_at'), 'performance_metrics', ['recorded_at'], unique=False)
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=240), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('auth_token', sa.String(length=40), nullable=False),
    sa.Column('grpc_port', sa.Integer(), nullable=False),
    sa.Column('workspace_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['agent_groups.id'], ),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('auth_token'),
    sa.UniqueConstraint('grpc_port'),
    sa.UniqueConstraint('name', 'group_id', name='uq_agent_name_group')
    )
    op.create_index(op.f('ix_agents_group_id'), 'agents', ['group_id'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_group_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_performance_metrics_recorded_at'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_agent_id'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_table('agent_groups')
    op.drop_index(op.f('ix_agent_events_created_at'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_agent_id'), table_name='agent_events')
    op.drop_table('agent_events')
    # ### end Alembic commands ###
